title: "우리 연구실"
description: "3D Vision • Dense Correspondence • Geodesic-aware Learning"
url: "https://<username>.github.io"
locale: ko

# GitHub Pages 호환 Jekyll 설정
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# 컬렉션 선언
collections:
  publications:
    output: true
    permalink: /publications/:title/
  people:
    output: true
    permalink: /people/:name/
  areas:
    output: true
    permalink: /areas/:name/

# 네비게이션 (세미콜론 X, 줄바꿈으로!)
nav:
  - title: "Home"
    url: "/"
  - title: "Research Areas"
    url: "/areas/"
  - title: "Publications"
    url: "/publications/"
  - title: "People"
    url: "/people/"
  - title: "Join Us"
    url: "/join/"

# 레이아웃 기본값
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "publications"
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "people"
    values:
      layout: single
  - scope:
      path: ""
      type: "areas"
    values:
      layout: single

# 검색(원하면 true)
search: true
